export const AUDIT_ACTIONS = {
  // System
  BOOTSTRAP_ADMIN_CREATED: "BOOTSTRAP_ADMIN_CREATED",

  // Auth domain
  USER_CREATED: "USER_CREATED",
  MANAGER_ASSIGNED: "MANAGER_ASSIGNED",

  // Leave domain
  LEAVE_CREATED: "LEAVE_CREATED",
  LEAVE_APPROVED: "LEAVE_APPROVED",
  LEAVE_REJECTED: "LEAVE_REJECTED",
  LEAVE_CANCELLED: "LEAVE_CANCELLED"
};
