

import { PERMISSIONS } from "./permission.js";

export const ROLE_PERMISSIONS = {
  admin: [
    // Employee data
    PERMISSIONS.EMPLOYEE_READ_ALL,
    PERMISSIONS.EMPLOYEE_UPDATE_ALL,

    // Salary & payroll
    PERMISSIONS.SALARY_VIEW_ALL,
    PERMISSIONS.PAYROLL_VIEW,
    PERMISSIONS.PAYROLL_GENERATE,

    // Leave
    PERMISSIONS.LEAVE_VIEW_ALL,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_REJECT,

    // System
    PERMISSIONS.ROLE_ASSIGN,
    PERMISSIONS.PERMISSION_ASSIGN
  ],

  HR: [
    // Employee data
    PERMISSIONS.EMPLOYEE_READ_ALL,

    // Salary & payroll
    PERMISSIONS.SALARY_VIEW_ALL,
    PERMISSIONS.PAYROLL_VIEW,
    PERMISSIONS.PAYROLL_GENERATE,

    // Leave
    PERMISSIONS.LEAVE_VIEW_ALL,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_REJECT
  ],

  manager: [
    // Employee data (usually team-level, enforced via ownership)
    PERMISSIONS.EMPLOYEE_READ_ALL,

    // Leave
    PERMISSIONS.LEAVE_VIEW_ALL,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_REJECT
  ],

  employee: [
    // Own data
    PERMISSIONS.EMPLOYEE_READ_SELF,
    PERMISSIONS.EMPLOYEE_UPDATE_SELF,

    // Salary
    PERMISSIONS.SALARY_VIEW_SELF,

    // Leave
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_VIEW_SELF
  ]
};
